  haproxy_app_name: myapp
  haproxy_mode: http
  haproxy_enable_stats: enable 
  haproxy_algorithm: roundrobin
  haproxy_backend_servers:
    - {name: name1, ip: 10.100.11.30, port: 80, paramstring: cookie A check}
    - {name: server2, ip: 10.100.10.40, port: 80, paramstring: cookie A check}
  haproxy_stats_users:
    - {username: joe, password: soap}
