all: # группа по умолчанию
  children: # указываем, что это вложенные хосты
    geek: # задаём имя группы, может быть любым
      hosts: #
        localhost: # указываем ip или FQDN
    prod:
      hosts:
        10.100.10.40:
          ansible_user: valera
          php_webserver_daemon: "nginx"
          php_default_version_debian: "7.4"
    haproxy:
      hosts:
        haproxy-vm:
          ansible_host: 10.10.10.30
    wordpress:
      hosts:
        wordpress-vm1:
          ansible_host: 10.100.10.40
        wordpress-vm2:
          ansible_host: 10.100.10.50
    database:
      hosts:
        database-vm:
          ansible_host: 10.100.10.60
    monitoring:
      hosts:
        monitor-vm:
          ansible_host: 10.100.10.70
